// ============================================================================
// MONGODB MODEL: Donation
// PURPOSE: Store all donation records with donor info and payment details
// FIELDS: Name, Email, Phone, Amount, Payment Method, Razorpay Receipt ID
// DATABASE: MongoDB (via Mongoose)
// ============================================================================

import mongoose from 'mongoose'

// ============================================================================
// DONATION SCHEMA - Define what data gets stored for each donation
// ============================================================================
const donationSchema = new mongoose.Schema(
  {
    // ====================================================================
    // DONOR PERSONAL INFORMATION
    // ====================================================================
    donorName: {
      type: String,
      required: true,
      trim: true,
      // Example: "Raj Kumar Singh"
    },
    
    donorEmail: {
      type: String,
      required: true,
      trim: true,
      lowercase: true,
      // Example: "raj.kumar@gmail.com"
    },
    
    donorPhone: {
      type: String,
      required: true,
      trim: true,
      // Example: "9876543210"
      // India phone format: 10 digits
    },

    // ====================================================================
    // DONATION AMOUNT
    // ====================================================================
    amount: {
      type: Number,
      required: true,
      min: 10,
      // In Rupees (₹)
      // Example: 500, 1000, 5000
    },

    // ====================================================================
    // PAYMENT INFORMATION - Razorpay Details
    // ============================================================ ====
    paymentMethod: {
      type: String,
      enum: ['UPI', 'Credit Card', 'Debit Card', 'Net Banking', 'Wallet', 'Other'],
      default: 'UPI',
      // Method used for donation
    },

    razorpayOrderId: {
      type: String,
      // Razorpay Order ID - created when payment initiated
      // Example: "order_1234567890abcd"
    },

    razorpayPaymentId: {
      type: String,
      // Razorpay Payment ID - after successful payment
      // Example: "pay_1234567890abcd"
    },

    razorpayReceiptId: {
      type: String,
      // Receipt ID from Razorpay for record keeping
      // Example: "receipt_123"
    },

    // ====================================================================
    // PAYMENT STATUS
    // ====================================================================
    paymentStatus: {
      type: String,
      enum: ['pending', 'completed', 'failed', 'refunded'],
      default: 'pending',
      // Status of the payment
    },

    // ====================================================================
    // TRANSACTION PROOF
    // ====================================================================
    transactionSignature: {
      type: String,
      // Razorpay signature for verification
      // Ensures payment is legitimate
    },

    // ====================================================================
    // NOTES (Optional)
    // ====================================================================
    notes: {
      type: String,
      default: '',
      // Any special notes about this donation
      // Example: "Donation for healthcare campaign"
    },

    // ====================================================================
    // TIMESTAMPS - Auto-generated by MongoDB
    // ====================================================================
    // createdAt: Automatically set when donation is created
    // updatedAt: Automatically updated when donation is modified
  },
  {
    timestamps: true,
    // This adds createdAt and updatedAt fields automatically
  }
)

// ============================================================================
// EXPORT MODEL
// This allows other files to import and use this model
// ============================================================================
export default mongoose.models.Donation || mongoose.model('Donation', donationSchema)
